export { default as about } from './about.js'
export { default as contact } from './contact.js'
export { default as nav } from './nav.js'
export { default as homepage } from './homepage.js'
export { default as watchlist } from './watchlist.js'
export { default as athlete } from './athlete.js'
